// This file is auto-generated by build.rs
// Do not edit manually
// --------------------------------------------------------
///GENERATED_BY

use regex::Regex;
use std::collections::HashMap;

pub const UNKNOWN_TOKEN: u32 = u32::MAX; // For unmatched characters

/// Token structure that represents a lexical token
#[derive(Debug, Clone, PartialEq)]
pub struct Token {
	pub kind: u32,
	pub value: String,
	pub row: usize,
	pub col: usize,
	pub length: usize,
	pub indent: usize,
	pub tag: isize,
}

impl Token {
	pub fn new(kind: u32, value: String, row: usize, col: usize, length: usize, indent: usize) -> Self {
		Token {
			kind,
			value,
			row,
			col,
			length,
			indent,
			tag: 0,
		}
	}
}

pub struct Lexer {
	input: String,
	pos: usize,
	row: usize,
	col: usize,
	regex_cache: HashMap<u32, Regex>,
	last_token_kind: Option<u32>,
}

impl Lexer {
	pub fn new(input: String) -> Self {
		let mut regex_cache = HashMap::new();
		////REG_EX_CODE
		Lexer {
			input,
			pos: 0,
			row: 1,
			col: 1,
			regex_cache,
			last_token_kind: None,
		}
	}

	pub fn next_token(&mut self) -> Option<Token> {
		if self.pos >= self.input.len() {
			return None;
		}

		let remaining = &self.input[self.pos..];
		let start_row = self.row;
		let start_col = self.col;

		// Calculate indent (spaces at the start of current line)
		let indent = self.calculate_line_indent();

		////RULE_MATCH_CODE

		// No pattern matched, consume one character
		let ch = remaining.chars().next().unwrap();
		let matched = ch.to_string();
		self.advance(&matched);
		let token = Token::new(UNKNOWN_TOKEN, matched, start_row, start_col, 1, indent);
		self.last_token_kind = Some(token.kind);
		Some(token)
	}

	fn calculate_line_indent(&self) -> usize {
		// Find the start of the current line
		let mut line_start = 0;
		let mut pos = 0;
		
		// Find the beginning of the current line
		while pos < self.pos {
			if self.input.chars().nth(pos) == Some('\n') {
				line_start = pos + 1;
			}
			pos += 1;
		}
		
		// Count spaces from the beginning of the line
		let line_content = &self.input[line_start..];
		line_content.chars().take_while(|&c| c == ' ').count()
	}

	fn match_cached_pattern(&self, input: &str, token_kind: u32) -> Option<String> {
		if let Some(regex) = self.regex_cache.get(&token_kind) {
			if let Some(mat) = regex.find(input) {
				return Some(mat.as_str().to_string());
			}
		}
		None
	}

	fn advance(&mut self, matched: &str) {
		for ch in matched.chars() {
			self.pos += ch.len_utf8();
			if ch == '\n' {
				self.row += 1;
				self.col = 1;
			} else {
				self.col += 1;
			}
		}
	}
}
